/**
 * Salesinteract API V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DashboardStatistics } from './dashboardStatistics';
import { History } from './history';
import { Quotation } from './quotation';
import { Task } from './task';


export interface Dashboard {
    history?: Array<History>;
    statistics?: DashboardStatistics;
    quotations?: Array<Quotation>;
    tasks?: Array<Task>;
}
