/**
 * Salesinteract API V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { DashboardStatisticsContacts } from './dashboardStatisticsContacts';
import { DashboardStatisticsTasks } from './dashboardStatisticsTasks';


export interface DashboardStatistics { 
    contacts?: DashboardStatisticsContacts;
    tasks?: DashboardStatisticsTasks;
}