/**
 * Salesinteract API V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TaskContact } from './taskContact';


export interface Task {
    id?: string;
    createdMs?: number;
    created?: string;
    due?: string;
    completed?: string;
    status?: string;
    outcome?: string;
    previousOutcome?: string;
    organisationName?: string;
    organisationId?: string;
    userId?: string;
    assignedId?: string;
    contact?: TaskContact;
    sales?: TaskContact;
    assigned?: TaskContact;
}
